# I'll use this workflow to run my main script every hour
name: Cron Job
on:    
  workflow_dispatch:
  schedule:
    - cron: '0 9-23 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install dependencies
      - name: Install
        run: npm install
      # Create a .env file
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      # Build the project
      - name: Build
        run: npm run build
      # Run the main script
      - name: Run
        run: npm run start
        